version: "3"
services:
  app:
    build:
      context: .
      dockerfile: DockerfileApp.dockerfile
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - PORT=${PORT}

  postgres:
    build:
      context: .
      dockerfile: DockerfileDB.dockerfile
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
