version: "3"
services:
  app:
    build:
      context: .
      dockerfile: DockerfileApp.dockerfile
      network: rs-network
    restart: always
    container_name: app
    hostname: app
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - PORT=${PORT}
    image: webmakaka/app

  postgres:
    build:
      context: .
      dockerfile: DockerfileDB.dockerfile
      network: rs-network
    restart: always
    container_name: postgres
    hostname: postgres
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}
    volumes:
      - ./PGDATA:/var/lib/postgresql/data
    image: webmakaka/postgres

networks:
  default:
    driver: bridge
    name: rs-network